/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package database;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.SpinnerDateModel;
import javax.swing.JComponent;
import java.text.SimpleDateFormat;


/**
 *
 * @author ASUS
 */
public class IssueBookFrame extends javax.swing.JFrame {
    
    JDBC jdbc = new JDBC();
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(IssueBookFrame.class.getName());

    /**
     * Creates new form IssueBookFrame
     */
    public IssueBookFrame() {
        initComponents();
    }
    
    private void showDatePicker(String fieldType){
        
        //creates a date spinner(shows tdy's date by default)
        JSpinner spinner = new JSpinner(new SpinnerDateModel());
        
        //format to show only date(Mysql's format y/m/d)
        JSpinner.DateEditor dateEditor = new JSpinner.DateEditor(spinner,"yyyy-MM-dd");
        spinner.setEditor(dateEditor);
        
        //show dialog with the spinner
        int result = JOptionPane.showConfirmDialog(this,spinner,
                "select " + fieldType + "Date",
                JOptionPane.OK_CANCEL_OPTION,
                JOptionPane.PLAIN_MESSAGE);
        
        //if user clicked ok, set the text field
        if(result == JOptionPane.OK_OPTION){
            java.util.Date selectedDate = (java.util.Date) spinner.getValue();
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            String formattedDate = sdf.format(selectedDate);
            
            if(fieldType.equals("Issue")){
                IssueDate_txtField.setText(formattedDate);
            }else{
                DueDate_txtField.setText(formattedDate);
            }
        }
        
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        jSeparator11 = new javax.swing.JSeparator();
        jSeparator12 = new javax.swing.JSeparator();
        jSeparator13 = new javax.swing.JSeparator();
        jSeparator14 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        issueBook_lbl = new javax.swing.JLabel();
        welcomeAdmin_lbl = new javax.swing.JLabel();
        BookId_lbl = new javax.swing.JLabel();
        StudentId_lbl = new javax.swing.JLabel();
        IssueDate_lbl = new javax.swing.JLabel();
        DueDate_lbl = new javax.swing.JLabel();
        calendar_btn1 = new javax.swing.JButton();
        IssueDate_txtField = new javax.swing.JTextField();
        DueDate_txtField = new javax.swing.JTextField();
        calendar_btn2 = new javax.swing.JButton();
        IssueBook_btn = new javax.swing.JButton();
        ClearData_btn = new javax.swing.JButton();
        issueBook_underline = new javax.swing.JSeparator();
        BookId_txtField = new javax.swing.JTextField();
        StudentId_txtField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(0, 204, 255));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel3.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel4.setBackground(new java.awt.Color(255, 51, 51));

        jButton2.setBackground(new java.awt.Color(51, 204, 255));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Back");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jButton2)
                .addContainerGap(167, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        issueBook_lbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        issueBook_lbl.setForeground(new java.awt.Color(255, 51, 0));
        issueBook_lbl.setText("Issue Book");
        jPanel1.add(issueBook_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 101, 20));

        welcomeAdmin_lbl.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        welcomeAdmin_lbl.setText("Welcome Admin!");
        jPanel1.add(welcomeAdmin_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, -1, -1));

        BookId_lbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BookId_lbl.setForeground(new java.awt.Color(255, 0, 51));
        BookId_lbl.setText("Book Id:");
        jPanel1.add(BookId_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 75, -1));

        StudentId_lbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        StudentId_lbl.setForeground(new java.awt.Color(255, 0, 51));
        StudentId_lbl.setText("Student Id:");
        jPanel1.add(StudentId_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 188, -1, -1));

        IssueDate_lbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        IssueDate_lbl.setForeground(new java.awt.Color(255, 0, 51));
        IssueDate_lbl.setText("Issue date:");
        jPanel1.add(IssueDate_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 242, -1, -1));

        DueDate_lbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        DueDate_lbl.setForeground(new java.awt.Color(255, 0, 51));
        DueDate_lbl.setText("Due date:");
        jPanel1.add(DueDate_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, -1, -1));

        calendar_btn1.setText("📅");
        calendar_btn1.setPreferredSize(new java.awt.Dimension(30, 25));
        calendar_btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calendar_btn1ActionPerformed(evt);
            }
        });
        jPanel1.add(calendar_btn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(283, 241, 56, -1));
        jPanel1.add(IssueDate_txtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 156, -1));

        DueDate_txtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DueDate_txtFieldActionPerformed(evt);
            }
        });
        jPanel1.add(DueDate_txtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, 160, -1));

        calendar_btn2.setText("📅");
        calendar_btn2.setPreferredSize(new java.awt.Dimension(30, 25));
        calendar_btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calendar_btn2ActionPerformed(evt);
            }
        });
        jPanel1.add(calendar_btn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 300, 56, -1));

        IssueBook_btn.setBackground(new java.awt.Color(255, 51, 51));
        IssueBook_btn.setForeground(new java.awt.Color(255, 255, 255));
        IssueBook_btn.setText("Issue Book");
        IssueBook_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IssueBook_btnActionPerformed(evt);
            }
        });
        jPanel1.add(IssueBook_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 360, -1, -1));

        ClearData_btn.setBackground(new java.awt.Color(255, 51, 51));
        ClearData_btn.setForeground(new java.awt.Color(255, 255, 255));
        ClearData_btn.setText("Clear Data");
        ClearData_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearData_btnActionPerformed(evt);
            }
        });
        jPanel1.add(ClearData_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 360, -1, -1));

        issueBook_underline.setForeground(new java.awt.Color(204, 204, 204));
        issueBook_underline.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(issueBook_underline, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 100, 65));
        jPanel1.add(BookId_txtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 230, -1));

        StudentId_txtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StudentId_txtFieldActionPerformed(evt);
            }
        });
        jPanel1.add(StudentId_txtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 230, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 457, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void StudentId_txtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StudentId_txtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StudentId_txtFieldActionPerformed

    private void DueDate_txtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DueDate_txtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DueDate_txtFieldActionPerformed

    private void IssueBook_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IssueBook_btnActionPerformed
        String bookId = BookId_txtField.getText().trim();
        String studentId = StudentId_txtField.getText().trim();
        String issueDate = IssueDate_txtField.getText().trim();
        String dueDate = DueDate_txtField.getText().trim();
        
        if(bookId.isEmpty() || studentId.isEmpty() || issueDate.isEmpty() || dueDate.isEmpty()){
            JOptionPane.showMessageDialog(this, "Please fill all fields!", "Error",JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        try{
            //check if book exists and is available
            String checkBookSql = "SELECT available_quantity FROM books WHERE book_id = ?";
            PreparedStatement checkBook = jdbc.getConnection().prepareStatement(checkBookSql);
            checkBook.setString(1, bookId);
            ResultSet bookResult = checkBook.executeQuery();
            
            if(!bookResult.next()){
                JOptionPane.showMessageDialog(this, "Book ID not found!","Error",JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            int availableQty = bookResult.getInt("available_quantity");
            if(availableQty <= 0){
                JOptionPane.showMessageDialog(this,"Book is not available!","Error",JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            //check if student exists
            String checkStudentSql = "SELECT * FROM members WHERE member_id = ?";
            PreparedStatement checkStudent = jdbc.getConnection().prepareStatement(checkStudentSql);
            checkStudent.setString(1,studentId);
            ResultSet StudentResult = checkStudent.executeQuery();
            
            if(!StudentResult.next()){
                JOptionPane.showMessageDialog(this, "Student ID not found!", "Error",JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            //insert borrowing record
            String insertSql = "INSERT INTO borrowings(member_id, book_id,issue_date, due_date) VALUES(?, ?, ?, ?)";
            PreparedStatement insertStmt = jdbc.getConnection().prepareStatement(insertSql);
            insertStmt.setString(1, studentId);
            insertStmt.setString(2, bookId);
            insertStmt.setString(3, issueDate);
            insertStmt.setString(4, dueDate);
            insertStmt.executeUpdate();
            
            //update book available quantity
            String UpdateSql = "UPDATE books SET available_quantity = available_quantity - 1 WHERE book_id = ?";
            PreparedStatement UpdateStmt = jdbc.getConnection().prepareStatement(UpdateSql);
            UpdateStmt.setString(1,bookId);
            UpdateStmt.executeUpdate();
            
            JOptionPane.showMessageDialog(this, "Book issued successfully!", "Success",JOptionPane.INFORMATION_MESSAGE );
            
            //Clear fields
            BookId_txtField.setText("");
            StudentId_txtField.setText("");
            IssueDate_txtField.setText("");
            DueDate_txtField.setText("");  
        
        }catch (Exception e){
                JOptionPane.showMessageDialog(this, "Error" + e.getMessage(),"Error", JOptionPane.ERROR_MESSAGE);
                e.printStackTrace();
            
        
        }
    }//GEN-LAST:event_IssueBook_btnActionPerformed

    private void ClearData_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearData_btnActionPerformed
    BookId_txtField.setText("");
    StudentId_txtField.setText("");
    IssueDate_txtField.setText("");
    DueDate_txtField.setText("");
    }//GEN-LAST:event_ClearData_btnActionPerformed

    private void calendar_btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calendar_btn1ActionPerformed
        showDatePicker("Issue");
    }//GEN-LAST:event_calendar_btn1ActionPerformed

    private void calendar_btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calendar_btn2ActionPerformed
        showDatePicker("Due");
    }//GEN-LAST:event_calendar_btn2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new IssueBookFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BookId_lbl;
    private javax.swing.JTextField BookId_txtField;
    private javax.swing.JButton ClearData_btn;
    private javax.swing.JLabel DueDate_lbl;
    private javax.swing.JTextField DueDate_txtField;
    private javax.swing.JButton IssueBook_btn;
    private javax.swing.JLabel IssueDate_lbl;
    private javax.swing.JTextField IssueDate_txtField;
    private javax.swing.JLabel StudentId_lbl;
    private javax.swing.JTextField StudentId_txtField;
    private javax.swing.JButton calendar_btn1;
    private javax.swing.JButton calendar_btn2;
    private javax.swing.JLabel issueBook_lbl;
    private javax.swing.JSeparator issueBook_underline;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JLabel welcomeAdmin_lbl;
    // End of variables declaration//GEN-END:variables
}
