/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package database;

/**
 *
 * @author ASUS
 */
public class ReturnBookFrame extends javax.swing.JFrame {
    
    JDBC jdbc = new JDBC();
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ReturnBookFrame.class.getName());

    /**
     * Creates new form ReturnBookFrame
     */
    public ReturnBookFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        ReturnBook_panel = new javax.swing.JPanel();
        WelcomeAdmin_lbl = new javax.swing.JLabel();
        ReturnBook_lbl = new javax.swing.JLabel();
        ReturnBook_underline = new javax.swing.JSeparator();
        BookId_lbl = new javax.swing.JLabel();
        studentId_lbl = new javax.swing.JLabel();
        Find_btn = new javax.swing.JButton();
        ReturnBook_btn = new javax.swing.JButton();
        BookId_txtField = new javax.swing.JTextField();
        studentId_txtField = new javax.swing.JTextField();
        BookDetails_panel = new javax.swing.JPanel();
        Image_panel = new javax.swing.JPanel();

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 420, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ReturnBook_panel.setBackground(new java.awt.Color(255, 255, 255));
        ReturnBook_panel.setForeground(new java.awt.Color(255, 255, 255));
        ReturnBook_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        WelcomeAdmin_lbl.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        WelcomeAdmin_lbl.setText("Welcome Admin!");
        ReturnBook_panel.add(WelcomeAdmin_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 6, 124, -1));

        ReturnBook_lbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ReturnBook_lbl.setForeground(new java.awt.Color(255, 51, 0));
        ReturnBook_lbl.setText("Return Book");
        ReturnBook_panel.add(ReturnBook_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 53, -1, -1));
        ReturnBook_panel.add(ReturnBook_underline, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 84, 108, 10));

        BookId_lbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BookId_lbl.setForeground(new java.awt.Color(255, 51, 0));
        BookId_lbl.setText("Book Id:");
        ReturnBook_panel.add(BookId_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, -1, -1));

        studentId_lbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        studentId_lbl.setForeground(new java.awt.Color(255, 51, 0));
        studentId_lbl.setText("Student Id:");
        ReturnBook_panel.add(studentId_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        Find_btn.setBackground(new java.awt.Color(0, 204, 255));
        Find_btn.setForeground(new java.awt.Color(255, 255, 255));
        Find_btn.setText("FIND");
        Find_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Find_btnActionPerformed(evt);
            }
        });
        ReturnBook_panel.add(Find_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 60, -1));

        ReturnBook_btn.setBackground(new java.awt.Color(255, 51, 0));
        ReturnBook_btn.setForeground(new java.awt.Color(255, 255, 255));
        ReturnBook_btn.setText("RETURN");
        ReturnBook_panel.add(ReturnBook_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 280, 80, -1));

        BookId_txtField.setForeground(new java.awt.Color(204, 204, 204));
        BookId_txtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BookId_txtFieldActionPerformed(evt);
            }
        });
        ReturnBook_panel.add(BookId_txtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 200, -1));

        studentId_txtField.setForeground(new java.awt.Color(204, 204, 204));
        ReturnBook_panel.add(studentId_txtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 200, -1));

        getContentPane().add(ReturnBook_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 0, 370, 380));

        BookDetails_panel.setBackground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout BookDetails_panelLayout = new javax.swing.GroupLayout(BookDetails_panel);
        BookDetails_panel.setLayout(BookDetails_panelLayout);
        BookDetails_panelLayout.setHorizontalGroup(
            BookDetails_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 280, Short.MAX_VALUE)
        );
        BookDetails_panelLayout.setVerticalGroup(
            BookDetails_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );

        getContentPane().add(BookDetails_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 280, 380));

        javax.swing.GroupLayout Image_panelLayout = new javax.swing.GroupLayout(Image_panel);
        Image_panel.setLayout(Image_panelLayout);
        Image_panelLayout.setHorizontalGroup(
            Image_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 280, Short.MAX_VALUE)
        );
        Image_panelLayout.setVerticalGroup(
            Image_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 370, Short.MAX_VALUE)
        );

        getContentPane().add(Image_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BookId_txtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BookId_txtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BookId_txtFieldActionPerformed

    private void Find_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Find_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Find_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ReturnBookFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BookDetails_panel;
    private javax.swing.JLabel BookId_lbl;
    private javax.swing.JTextField BookId_txtField;
    private javax.swing.JButton Find_btn;
    private javax.swing.JPanel Image_panel;
    private javax.swing.JButton ReturnBook_btn;
    private javax.swing.JLabel ReturnBook_lbl;
    private javax.swing.JPanel ReturnBook_panel;
    private javax.swing.JSeparator ReturnBook_underline;
    private javax.swing.JLabel WelcomeAdmin_lbl;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel studentId_lbl;
    private javax.swing.JTextField studentId_txtField;
    // End of variables declaration//GEN-END:variables
}
